In [80]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [95]:
df = pd.read_csv('dataset_mood_smartphone.csv', index_col = 0)
df.head()

        id                     time variable  value
1  AS14.01  2014-02-26 13:00:00.000     mood    6.0
2  AS14.01  2014-02-26 15:00:00.000     mood    6.0
3  AS14.01  2014-02-26 18:00:00.000     mood    6.0
4  AS14.01  2014-02-26 21:00:00.000     mood    7.0
5  AS14.01  2014-02-27 09:00:00.000     mood    6.0

In [83]:
#Variable names
variables = df["variable"].unique()
variables

19

In [84]:
#Variable names
variables = df["variable"].unique()
variables

In [85]:
#time to datetime type
df['time'] = pd.to_datetime(df['time'])

### Exploratory analysis

In [86]:
#number of instances
n = len(df)
n

376912

In [87]:
#number of missing data
missing = df.isnull().sum()
missing

id            0
time          0
variable      0
value       202
dtype: int64

In [88]:
#time window of complete data set
print(df['time'].min())
print(df['time'].max())

In [ ]:
#creating a summary of the variables
descriptive_stats_list = []

for i in variables:
    temp_df = df.loc[df['variable'] == i].copy()
    temp_df = temp_df.drop(['time'], axis=1)

    stats = temp_df.describe()
    median = temp_df['value'].median()
    skewness = temp_df['value'].skew()
    kurtosis = temp_df['value'].kurt()

    missing_values = temp_df.isnull().sum()
    variable_stats = {
        'Stats': stats,
        "Median": median,
        'Missing_values': missing_values,
        'Skewness': skewness,
        "Kurtosis": kurtosis

    }
    descriptive_stats_list.append((i, variable_stats))

for i, stats_data in descriptive_stats_list:
    print(f"Descriptive stats for variable {i}:")
    print(stats_data['Stats'])
    print(f"Missing values for variable {i}:")
    print(stats_data['Missing_values'])
    print(f"Skewness of  {i}:", stats_data['Skewness'])
    print(f"median of  {i}:",  stats_data['Median'])
    print("\n")

In [ ]:
for i in variables:
    subset = df[df['variable'] == i]
    
    plt.figure(figsize=(10, 6))
    plt.hist(subset['value'], bins=50, edgecolor='black', alpha=0.7)
    plt.title(f"Histogram for {i}")
    plt.xlabel("Value")
    plt.ylabel("Frequency")
    plt.grid(True)
    plt.show()

In [ ]:
# df['value'] = df.groupby(['id', 'variable'])['value'].fillna(method='ffill')
# df['value'] = df.groupby(['id', 'variable'])['value'].fillna(method='bfill')

In [13]:
# missing = df.isnull().sum()
# missing

## Second way

In [ ]:
#add new date column
df['date'] = df['time'].dt.date
daily_median = df.groupby(['id', 'variable', 'date'])['value'].transform('median')
df['value'] = df['value'].fillna(daily_median)

In [15]:
missing_rows = df[df['value'].isnull()]
missing_rows

            id                time            variable  value        date
15038  AS14.24 2014-05-10 09:00:00  circumplex.valence    NaN  2014-05-10
15039  AS14.24 2014-05-10 12:00:00  circumplex.valence    NaN  2014-05-10
15040  AS14.24 2014-05-10 18:00:00  circumplex.valence    NaN  2014-05-10
15041  AS14.24 2014-05-10 21:00:00  circumplex.valence    NaN  2014-05-10
15167  AS14.24 2014-06-07 12:00:00  circumplex.valence    NaN  2014-06-07

In [16]:
daily_medians = df.groupby(['id', 'variable', 'date'])['value'].median().reset_index(name='daily_median')

# shift median to previous day (per id & variable)
daily_medians['prev_day'] = daily_medians.groupby(['id', 'variable'])['daily_median'].shift(1).copy()
daily_medians['next_day'] = daily_medians.groupby(['id', 'variable'])['daily_median'].shift(-1).copy()

# merge shifted values back to the main df
df = df.merge(daily_medians[['id', 'variable', 'date', 'prev_day', 'next_day']], 
              on=['id', 'variable', 'date'], how='left')

# fill  NaN values in using the previous day's median
df['value'] = df['value'].fillna((df['prev_day']+df['next_day'])/2)

# drop the now redundand column
df.drop(columns=['prev_day'], inplace=True)
df.drop(columns=['next_day'], inplace=True)

In [17]:
missing = df.isnull().sum()
missing

id          0
time        0
variable    0
value       0
date        0
dtype: int64